name: 'analytics_chrisw'
version: '1.0.0'
config-version: 2

profile: 'default'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

vars:
  'dbt_date:time_zone': 'America/New_York'

models:
  analytics_chrisw:
    staging:
    intermediate:
    marts: